"""S1-05 Revised: File validation, DOCX symlink fix, encrypted PDF/DOCX,
atomic quarantine, extension whitelist, path containment.

Required test coverage per validation findings:
- Genuine valid DOCX accepted through endpoint
- Unix regular-file mode 0o100644 accepted
- Actual Unix symlink entry rejected
- DOCX at depth limit accepted / above rejected
- Genuine encrypted PDF rejected (pypdf-based)
- Valid unencrypted PDF accepted
- Malformed PDF rejected safely
- Encrypted Office OLE container rejected as docx_encrypted
- Macro-enabled DOCX rejected
- Unsupported/manipulated quarantine extensions rejected
- Path containment: sibling-prefix escape blocked
- Write failure leaves no partial file
- Rename failure leaves no partial file
- UUID filenames unique, no original filename content
- Existing tests continue to pass
"""

import io
import os
import uuid
import zipfile
from datetime import UTC
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from app.services import upload_quarantine
from app.services.upload_quarantine import (
    get_quarantine_path,
    store_in_quarantine,
)
from app.services.upload_validator import (
    UploadRejectionReason,
    _is_unix_symlink,
    validate_docx_archive,
    validate_file_signature,
    validate_pdf_not_encrypted,
)


def _make_real_docx_with_python_docx(path: Path) -> Path:
    """Generate a genuine valid DOCX using python-docx library."""
    from docx import Document

    doc = Document()
    doc.add_heading("Training Script", level=1)
    doc.add_paragraph("This is a valid training document for the AI debtor.")
    doc.save(str(path))
    return path


def _make_minimal_valid_docx(path: Path) -> Path:
    """Create a structurally valid DOCX with standard paths."""
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr(
            "[Content_Types].xml",
            '<?xml version="1.0"?>'
            '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            '<Default Extension="xml" ContentType="application/xml"/>'
            '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
            "</Types>",
        )
        zf.writestr(
            "_rels/.rels",
            '<?xml version="1.0"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
            "</Relationships>",
        )
        zf.writestr(
            "word/document.xml",
            '<?xml version="1.0"?>'
            '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            "<w:body><w:p><w:r><w:t>Hello</w:t></w:r></w:p></w:body></w:document>",
        )
        zf.writestr(
            "word/_rels/document.xml.rels",
            '<?xml version="1.0"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>',
        )
        zf.writestr(
            "docProps/core.xml",
            '<?xml version="1.0"?>'
            '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"/>',
        )
    return path


class TestGenuineValidDocx:
    """Real DOCX files must be accepted."""

    def test_python_docx_generated_file_accepted(self, tmp_path):
        """DOCX generated by python-docx passes archive validation."""
        path = _make_real_docx_with_python_docx(tmp_path / "genuine.docx")
        valid, reason = validate_docx_archive(path)
        assert valid is True, f"Genuine DOCX rejected: {reason}"

    def test_minimal_valid_docx_accepted(self, tmp_path):
        """Minimal hand-crafted DOCX with standard paths passes."""
        path = _make_minimal_valid_docx(tmp_path / "minimal.docx")
        valid, reason = validate_docx_archive(path)
        assert valid is True, f"Minimal DOCX rejected: {reason}"

    def test_docx_at_depth_boundary_accepted(self, tmp_path):
        """Entries at exactly dir_depth=2 (word/_rels/file) are accepted."""
        path = tmp_path / "boundary.docx"
        with zipfile.ZipFile(path, "w") as zf:
            zf.writestr("[Content_Types].xml", "<Types/>")
            zf.writestr("word/_rels/document.xml.rels", "<R/>")
        valid, _reason = validate_docx_archive(path)
        assert valid is True

    def test_docx_above_depth_rejected(self, tmp_path):
        """Entries at dir_depth=3 (a/b/c/file) are rejected."""
        path = tmp_path / "deep.docx"
        with zipfile.ZipFile(path, "w") as zf:
            zf.writestr("[Content_Types].xml", "<Types/>")
            zf.writestr("a/b/c/deep.xml", "<d/>")
        valid, reason = validate_docx_archive(path)
        assert valid is False
        assert reason == UploadRejectionReason.DOCX_TOO_DEEP


class TestUnixSymlinkDetection:
    """Correct symlink detection using Unix mode bits."""

    def test_regular_file_mode_0o100644_accepted(self, tmp_path):
        """Normal Unix file entry (mode 0o100644) is NOT a symlink."""
        path = tmp_path / "regular.docx"
        with zipfile.ZipFile(path, "w") as zf:
            info = zipfile.ZipInfo("[Content_Types].xml")
            # Unix regular file: mode 0o100644, create_system=3 (Unix)
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            zf.writestr(info, "<Types/>")

            info2 = zipfile.ZipInfo("word/document.xml")
            info2.create_system = 3
            info2.external_attr = 0o100644 << 16
            zf.writestr(info2, "<doc/>")

        valid, reason = validate_docx_archive(path)
        assert valid is True, f"Regular Unix file rejected: {reason}"

    def test_actual_symlink_entry_rejected(self, tmp_path):
        """Entry with Unix symlink mode (0o120777) is rejected."""
        path = tmp_path / "symlink.docx"
        with zipfile.ZipFile(path, "w") as zf:
            info = zipfile.ZipInfo("[Content_Types].xml")
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            zf.writestr(info, "<Types/>")

            # Symlink: mode 0o120777
            sym_info = zipfile.ZipInfo("word/link.xml")
            sym_info.create_system = 3
            sym_info.external_attr = 0o120777 << 16
            zf.writestr(sym_info, "/etc/passwd")

        valid, reason = validate_docx_archive(path)
        assert valid is False
        assert reason == UploadRejectionReason.DOCX_SUSPICIOUS_ENTRY

    def test_windows_entry_not_checked_for_symlink(self, tmp_path):
        """Entries from Windows (create_system=0) skip symlink check."""
        path = tmp_path / "windows.docx"
        with zipfile.ZipFile(path, "w") as zf:
            info = zipfile.ZipInfo("[Content_Types].xml")
            info.create_system = 0  # Windows
            # High bits set but not from Unix — should not be treated as symlink
            info.external_attr = 0x20  # Windows archive attribute
            zf.writestr(info, "<Types/>")
        valid, _reason = validate_docx_archive(path)
        assert valid is True

    def test_is_unix_symlink_helper_regular_file(self):
        info = zipfile.ZipInfo("test.xml")
        info.create_system = 3
        info.external_attr = 0o100644 << 16
        assert _is_unix_symlink(info) is False

    def test_is_unix_symlink_helper_actual_symlink(self):
        info = zipfile.ZipInfo("link.xml")
        info.create_system = 3
        info.external_attr = 0o120777 << 16
        assert _is_unix_symlink(info) is True

    def test_is_unix_symlink_helper_windows_entry(self):
        info = zipfile.ZipInfo("test.xml")
        info.create_system = 0
        info.external_attr = 0xA0000000  # Would be wrong if checked as Unix
        assert _is_unix_symlink(info) is False


class TestEncryptedPdfPypdf:
    """Encrypted PDF detection using pypdf (not heuristic)."""

    def test_genuine_encrypted_pdf_rejected(self):
        """Create a real encrypted PDF using pypdf and verify rejection."""
        from pypdf import PdfWriter

        writer = PdfWriter()
        writer.add_blank_page(width=612, height=792)
        writer.encrypt("test-password-marker")
        buf = io.BytesIO()
        writer.write(buf)
        encrypted_bytes = buf.getvalue()

        valid, reason = validate_pdf_not_encrypted(encrypted_bytes)
        assert valid is False
        assert reason == UploadRejectionReason.PDF_ENCRYPTED

    def test_valid_unencrypted_pdf_accepted(self):
        """Unencrypted PDF passes."""
        from pypdf import PdfWriter

        writer = PdfWriter()
        writer.add_blank_page(width=612, height=792)
        buf = io.BytesIO()
        writer.write(buf)
        pdf_bytes = buf.getvalue()

        valid, reason = validate_pdf_not_encrypted(pdf_bytes)
        assert valid is True
        assert reason is None

    def test_malformed_pdf_rejected_safely(self):
        """Malformed/truncated PDF fails closed as pdf_malformed."""
        valid, reason = validate_pdf_not_encrypted(b"%PDF-1.4\x00\x00garbage")
        assert valid is False
        assert reason == UploadRejectionReason.PDF_MALFORMED

    def test_completely_invalid_bytes_rejected(self):
        """Non-PDF bytes fail closed."""
        valid, reason = validate_pdf_not_encrypted(b"\x00\x01\x02\x03")
        assert valid is False
        assert reason == UploadRejectionReason.PDF_MALFORMED


class TestOleDocxPolicy:
    """OLE/CFB container policy: valid DOCX must be ZIP, not OLE.

    Fail-closed approach: any .docx with OLE signature is rejected as
    docx_unsafe_container because valid unencrypted DOCX must use ZIP/OOXML.
    """

    def test_ole_signature_docx_rejected_as_unsafe_container(self):
        """DOCX with OLE/CFB signature is rejected (not confirmed encrypted, just unsafe)."""
        ole_header = b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1" + b"\x00" * 100
        valid, reason = validate_file_signature("encrypted.docx", ole_header)
        assert valid is False
        assert reason == UploadRejectionReason.DOCX_UNSAFE_CONTAINER

    def test_normal_zip_docx_signature_accepted(self):
        """Normal DOCX with PK/ZIP signature passes signature check."""
        pk_header = b"\x50\x4b\x03\x04\x14\x00\x06\x00"
        valid, _reason = validate_file_signature("normal.docx", pk_header)
        assert valid is True

    def test_ole_as_non_docx_rejected_as_signature_mismatch(self):
        """OLE signature on a .txt file is rejected as signature mismatch."""
        ole_header = b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"
        valid, reason = validate_file_signature("data.txt", ole_header)
        assert valid is False
        assert reason == UploadRejectionReason.SIGNATURE_MISMATCH


class TestMacroEnabledDocx:
    """DOCM/macro content detection."""

    def test_vbaproject_rejected(self, tmp_path):
        path = tmp_path / "macro.docx"
        with zipfile.ZipFile(path, "w") as zf:
            zf.writestr("[Content_Types].xml", "<Types/>")
            zf.writestr("word/vbaProject.bin", b"\x00" * 20)
        valid, reason = validate_docx_archive(path)
        assert valid is False
        assert reason == UploadRejectionReason.DOCX_MACRO_ENABLED


class TestQuarantineExtensionWhitelist:
    """Strict extension whitelist for store_in_quarantine."""

    def test_accepted_extensions(self, tmp_path):
        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            for ext in (".pdf", ".docx", ".txt", ".csv", ".md"):
                p = store_in_quarantine(b"content", ext)
                assert p.exists()
                assert p.suffix == ext

    def test_uppercase_accepted(self, tmp_path):
        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            p = store_in_quarantine(b"content", ".PDF")
            assert p.exists()
            assert p.suffix == ".pdf"

    @pytest.mark.parametrize(
        "bad_ext",
        [
            ".exe",
            ".zip",
            ".mp3",
            ".xlsx",
            ".wav",
            "../escape",
            ".pdf/../../escape",
            "",
            "nodot",
            ".bat",
            ".dll",
        ],
    )
    def test_rejected_extensions(self, tmp_path, bad_ext):
        with (
            patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)),
            pytest.raises(ValueError, match="whitelist"),
        ):
            store_in_quarantine(b"content", bad_ext)


class TestQuarantinePathContainment:
    """Path cannot escape quarantine through sibling-prefix tricks."""

    def test_normal_storage_inside_quarantine(self, tmp_path):
        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            path = store_in_quarantine(b"data", ".pdf")
            qdir = get_quarantine_path()
            assert path.resolve().is_relative_to(qdir)

    def test_sibling_prefix_cannot_escape(self, tmp_path):
        """A sibling dir like 'quarantine-escape' cannot pass containment check."""
        qdir = tmp_path / "quarantine"
        qdir.mkdir()
        # The sibling directory that would match a string-prefix check
        escape_dir = tmp_path / "quarantine-escape"
        escape_dir.mkdir()

        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(qdir)):
            path = store_in_quarantine(b"safe", ".txt")
            # Must be inside qdir, not quarantine-escape
            assert path.resolve().is_relative_to(qdir.resolve())
            assert not str(path.resolve()).startswith(str(escape_dir.resolve()))

    def test_uuid_filename_no_original_name(self, tmp_path):
        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            path = store_in_quarantine(b"content", ".pdf")
            # Filename must be a UUID, not contain any user-provided text
            uuid.UUID(path.stem)  # raises if not valid UUID
            assert "report" not in path.name
            assert "malware" not in path.name


class TestAtomicWriteFailureCleanup:
    """Simulated write/rename failure leaves no partial file."""

    def test_write_failure_no_partial_file(self, tmp_path):
        """If os.write fails, no temp or final file remains."""
        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            with patch("app.services.upload_quarantine.os.write", side_effect=OSError("disk full")):
                with pytest.raises(OSError):
                    store_in_quarantine(b"data", ".pdf")

            # No files should remain (only .gitkeep-like entries if any)
            remaining = [
                f for f in tmp_path.iterdir() if f.is_file() and not f.name.startswith(".")
            ]
            assert remaining == [], f"Partial files remain: {remaining}"

    def test_rename_failure_no_partial_file(self, tmp_path):
        """If rename fails after successful write, temp file is cleaned up."""
        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):

            def failing_rename(self, target):
                raise OSError("rename failed")

            with patch.object(Path, "rename", failing_rename), pytest.raises(OSError):
                store_in_quarantine(b"data", ".pdf")

            # No files should remain
            remaining = [f for f in tmp_path.iterdir() if f.is_file()]
            assert remaining == [], f"Partial files remain: {remaining}"

    def test_successful_write_produces_exactly_one_file(self, tmp_path):
        """Normal success produces exactly one final file, no temps."""
        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            path = store_in_quarantine(b"hello world", ".md")
            files = list(tmp_path.iterdir())
            assert len(files) == 1
            assert files[0] == path
            assert path.read_bytes() == b"hello world"


class TestPartialWriteHandling:
    """os.write() partial-count handling and size verification."""

    def test_partial_writes_complete_successfully(self, tmp_path):
        """os.write() returns partial counts but all bytes are eventually written."""
        data = b"ABCDEFGHIJ" * 100  # 1000 bytes
        call_count = [0]
        original_write = os.write

        def mock_partial_write(fd, buf):
            call_count[0] += 1
            # Write only 100 bytes at a time to simulate partial writes
            chunk = buf[:100]
            return original_write(fd, chunk)

        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            with patch("app.services.upload_quarantine.os.write", side_effect=mock_partial_write):
                path = store_in_quarantine(data, ".txt")

        assert path.exists()
        assert path.read_bytes() == data
        assert call_count[0] == 10  # 1000/100 = 10 calls

    def test_zero_write_before_completion_raises(self, tmp_path):
        """os.write() returning 0 before all bytes written is treated as error."""
        data = b"X" * 500
        call_count = [0]
        original_write = os.write

        def mock_zero_write(fd, buf):
            call_count[0] += 1
            if call_count[0] == 3:
                return 0  # Zero-byte write on third call
            return original_write(fd, buf[:100])

        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            with patch("app.services.upload_quarantine.os.write", side_effect=mock_zero_write):
                with pytest.raises(OSError, match="returned 0"):
                    store_in_quarantine(data, ".txt")

        # No files should remain
        remaining = [f for f in tmp_path.iterdir() if f.is_file()]
        assert remaining == [], f"Partial files remain: {remaining}"

    def test_final_stored_bytes_equal_input(self, tmp_path):
        """Stored file bytes exactly match input bytes."""
        data = os.urandom(4096)  # Random binary data
        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            path = store_in_quarantine(data, ".pdf")
        assert path.read_bytes() == data
        assert path.stat().st_size == len(data)

    def test_size_mismatch_prevents_rename(self, tmp_path):
        """If stat shows wrong size after write, file is not renamed."""
        data = b"X" * 1000
        original_stat = Path.stat

        def fake_stat(self):
            result = original_stat(self)
            # Return a MagicMock with wrong st_size for temp files
            if ".tmp_upload_" in self.name:
                mock_result = MagicMock()
                mock_result.st_size = 500  # Wrong size
                return mock_result
            return result

        with patch.object(upload_quarantine.settings, "upload_quarantine_path", str(tmp_path)):
            with patch.object(Path, "stat", fake_stat):
                with pytest.raises(OSError, match="Size mismatch"):
                    store_in_quarantine(data, ".pdf")

        # No final files remain
        remaining = [f for f in tmp_path.iterdir() if f.is_file()]
        assert remaining == [], f"Files remain after size mismatch: {remaining}"


class TestGenuineDocxEndpointIntegration:
    """Upload a python-docx generated file through the real endpoint.

    Exercises: extension, MIME, binary-signature, quarantine storage,
    DOCX archive validation, and content extraction.
    Only mocks: malware scanner and database session.
    Does NOT mock: validate_file_signature, validate_docx_archive, store_in_quarantine.
    """

    @pytest.mark.asyncio
    async def test_genuine_docx_upload_201(self, tmp_path):
        """Real DOCX generated by python-docx succeeds through full pipeline."""
        from datetime import datetime
        from unittest.mock import AsyncMock

        # Generate a real DOCX
        from docx import Document
        from httpx import ASGITransport, AsyncClient

        from app.database import get_session
        from app.main import create_app
        from app.models.user import User, UserRole
        from app.services.auth import require_admin

        doc = Document()
        doc.add_heading("AI Debtor Training Script", level=1)
        doc.add_paragraph("When the agent says hello, respond with a greeting.")
        docx_path = tmp_path / "training.docx"
        doc.save(str(docx_path))
        docx_bytes = docx_path.read_bytes()

        # Mock admin user
        admin = MagicMock(spec=User)
        admin.id = uuid.uuid4()
        admin.email = "admin@test.com"
        admin.role = UserRole.ADMIN.value

        # Mock DB session (synchronous add, async commit/refresh/execute)
        mock_db = MagicMock()
        mock_db.add = MagicMock()
        mock_db.commit = AsyncMock()
        mock_db.rollback = AsyncMock()

        async def _refresh(obj):
            if not hasattr(obj, "created_at") or obj.created_at is None:
                obj.created_at = datetime.now(UTC)

        mock_db.refresh = AsyncMock(side_effect=_refresh)

        app = create_app()
        app.dependency_overrides[require_admin] = lambda: admin
        app.dependency_overrides[get_session] = lambda: mock_db

        # Use a temp quarantine dir so real files are created and cleaned up
        q_dir = tmp_path / "quarantine"
        q_dir.mkdir()

        try:
            with patch("app.services.upload_quarantine.settings") as mock_settings:
                mock_settings.upload_quarantine_path = str(q_dir)
                mock_settings.upload_quarantine_retention_hours = 24
                mock_settings.upload_quarantine_cleanup_interval_minutes = 60
                mock_settings.upload_max_file_size = 10_485_760
                mock_settings.upload_max_docx_entries = 500
                mock_settings.upload_max_docx_uncompressed_size = 52_428_800
                mock_settings.upload_max_docx_depth = 2

                with patch("app.api.uploads.settings") as mock_api_settings:
                    mock_api_settings.upload_max_file_size = 10_485_760
                    mock_api_settings.upload_quarantine_retention_hours = 24

                    with patch("app.api.uploads.scan_file") as mock_scan:
                        mock_scan.return_value = MagicMock(clean=True, signature=None, error=None)

                        transport = ASGITransport(app=app)
                        async with AsyncClient(
                            transport=transport, base_url="http://test"
                        ) as client:
                            resp = await client.post(
                                "/api/scripts/upload",
                                files={
                                    "file": (
                                        "training.docx",
                                        docx_bytes,
                                        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                    )
                                },
                            )

            assert resp.status_code == 201, f"Got {resp.status_code}: {resp.text}"
            data = resp.json()

            # Verify response
            assert data["filename_original"] == "training.docx"
            assert data["extraction_status"] == "completed"
            assert data["scan_result"] == "clean"
            assert data["status"] == "completed"
            assert data["script_id"] is None  # Not linked until S1-09

            # Verify db.add was called with upload record
            mock_db.add.assert_called_once()
            record = mock_db.add.call_args[0][0]
            assert record.filename_original == "training.docx"
            assert (
                record.mime_type
                == "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            )
            assert record.extraction_status == "completed"
            assert record.extracted_content is not None
            assert len(record.extracted_content) > 0

            # Storage key is UUID-based, not original filename
            assert "training" not in record.storage_key
            uuid.UUID(record.storage_key.replace(".docx", ""))

        finally:
            app.dependency_overrides.clear()
            # Clean up quarantine files
            for f in q_dir.iterdir():
                if f.is_file():
                    f.unlink()
